name: Unit Test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: install
        run: |
          npm install
      - name: test
        run: |
          npm run test

      - name: coverage
        run: |
          npm run coverage
